spring:
  datasource:
    url: jdbc:mysql://${database.development.host}/${database.name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}